[package]
name = "osmosis-authenticators"
version = "0.22.0-alpha.2"
description = "utilities for writing osmosis authenticators"
authors = ["osmosis-contributors"]
edition = "2021"
license = "MIT"

[dependencies]
cosmwasm-schema = "1.1.3"
cosmwasm-std = {version = "1.4"}
serde-json-wasm = "1.0.0"
sha2 = "0.10.8"

[package.metadata]
documentation = "https://docs.rs/osmosis_authenticators"
repository = "https://github.com//osmosis-labs/osmosis-rust"
