[package]
authors = ["osmosis-contributors"]
description = "utilities for writing osmosis authenticators"
edition = "2021"
license = "MIT"
name = "osmosis-authenticators"
version = "0.22.0-alpha.17"

[dependencies]
cosmwasm-schema = "1.1.3"
cosmwasm-std = {version = "1.4"}
sha2 = "0.10.8"

[dev-dependencies]
serde_json = "1.0.114"

[package.metadata]
documentation = "https://docs.rs/osmosis_authenticators"
repository = "https://github.com//osmosis-labs/osmosis-rust"
